## => Site Settings
##############################
baseurl : ''# does not include hostname
title   : Your Site Title
description: > # this means to ignore newlines until "Language & timezone"
  Your Site Description
